import { motion } from 'framer-motion';
import { Check, Coins, Sparkles, Zap } from 'lucide-react';
import { GrindlyCharacter } from './GrindlyCharacter';

export default function CompletionAnimation({ quest, reward = {}, user }) {
  const attribute = reward.attribute || reward.attribute_gain;
  const attributeValue = reward.attributeValue || reward.attribute_gain_value;
  return <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="pointer-events-none fixed inset-0 z-50 grid place-items-center bg-ink/70 p-5 backdrop-blur-md"><motion.div initial={{ scale: .72, y: 20 }} animate={{ scale: 1, y: 0 }} transition={{ type: 'spring', stiffness: 180 }} className="relative w-full max-w-sm overflow-hidden rounded-[2rem] border border-lime/35 bg-gradient-to-br from-[#1a2b1e] to-panel p-7 text-center shadow-[0_0_80px_rgba(200,241,105,.18)]"><div className="absolute inset-0 opacity-30 [background-image:radial-gradient(circle_at_50%_0%,#c8f169,transparent_48%)]" /><div className="relative"><GrindlyCharacter mood="happy" size="md" /><p className="eyebrow mt-4 text-lime">Quest complete</p><h2 className="mt-2 font-display text-2xl font-extrabold">{quest.title}</h2><div className="mt-6 grid grid-cols-2 gap-3"><RewardValue icon={Zap} label="XP earned" value={`+${reward.xp ?? quest.xp ?? 0}`} tone="text-lime" /><RewardValue icon={Coins} label="Coins earned" value={`+${reward.coins ?? quest.coins ?? 0}`} tone="text-[#ffd27a]" /></div>{attribute && <div className="mt-4 flex items-center justify-center gap-2 rounded-xl border border-[#8fd9ff]/25 bg-[#8fd9ff]/10 px-3 py-2 text-sm font-bold text-[#a8e3ff]"><Sparkles size={15} /> {attribute} +{attributeValue || 1}</div>}<div className="mt-6 flex items-center justify-center gap-2 text-xs font-bold text-[#8ff0b6]"><span className="grid h-6 w-6 place-items-center rounded-full bg-[#5bdc96]/15"><Check size={13} /></span>{user ? `Level ${user.level} progression updated` : 'Progression updated'}</div></div></motion.div></motion.div>;
}

function RewardValue({ icon: Icon, label, value, tone }) { return <div className="rounded-2xl border border-white/10 bg-black/15 px-3 py-3"><Icon size={17} className={`mx-auto ${tone}`} /><p className={`mt-2 font-display text-xl font-extrabold ${tone}`}>{value}</p><p className="mt-1 text-[.62rem] text-muted">{label}</p></div>; }
