import { useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { ArrowRight, Bot, Check, ChevronLeft, Sparkles, WandSparkles } from 'lucide-react';
import { avatarOptions } from '../data/mockData';

export default function Onboarding({ onComplete }) {
  const [step, setStep] = useState(0);
  const [name, setName] = useState('');
  const [username, setUsername] = useState('');
  const [selectedAvatar, setSelectedAvatar] = useState('avatar-1');
  const [customAvatar, setCustomAvatar] = useState('');
  const totalSteps = 5;
  const complete = () => onComplete({ id: 'user-1', username: username || 'Adventurer', displayName: name || 'Adventurer', avatar: customAvatar || selectedAvatar, level: 1, experience: 0, nextLevelExp: 1000, coins: 250, streak: 0, globalRank: 9999, friendRank: 0, joinedDate: new Date().toISOString().split('T')[0] });
  const steps = [<WelcomeStep key="welcome" name={name} setName={setName} />, <AvatarStep key="avatar" selected={selectedAvatar} setSelected={setSelectedAvatar} custom={customAvatar} setCustom={setCustomAvatar} />, <UsernameStep key="username" username={username} setUsername={setUsername} />, <GuideStep key="guide" />, <TutorialStep key="tutorial" />];
  return <div className="relative flex min-h-screen items-center justify-center overflow-hidden bg-ink px-5 py-8"><div className="absolute left-1/2 top-0 h-[30rem] w-[30rem] -translate-x-1/2 rounded-full bg-lime/10 blur-[120px]" /><div className="relative w-full max-w-2xl"><div className="mb-8 flex items-center justify-between"><div className="flex items-center gap-2"><span className="brand-mark">G</span><span className="font-display font-bold">Grindly</span></div><span className="eyebrow">Setup · 0{step + 1}/0{totalSteps}</span></div><div className="mb-8 flex gap-1.5">{Array.from({ length: totalSteps }, (_, index) => <div key={index} className={`h-1 flex-1 rounded-full transition ${index <= step ? 'bg-lime' : 'bg-white/10'}`} />)}</div><AnimatePresence mode="wait"><motion.div key={step} initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -20 }} transition={{ duration: .22 }}>{steps[step]}</motion.div></AnimatePresence><div className="mt-8 flex items-center justify-between">{step > 0 ? <button onClick={() => setStep((current) => current - 1)} className="btn-secondary flex items-center gap-2"><ChevronLeft size={16} /> Back</button> : <span />}{step < totalSteps - 1 ? <button disabled={step === 0 && !name.trim()} onClick={() => setStep((current) => current + 1)} className="btn-primary flex items-center gap-2 disabled:cursor-not-allowed disabled:opacity-40">Continue <ArrowRight size={16} /></button> : <button onClick={complete} className="btn-primary flex items-center gap-2">Enter Grindly <Sparkles size={16} /></button>}</div></div></div>;
}

function WelcomeStep({ name, setName }) { return <div className="mx-auto max-w-xl text-center"><div className="mx-auto grid h-16 w-16 place-items-center rounded-3xl bg-lime text-ink"><WandSparkles size={29} /></div><p className="eyebrow mt-7 text-lime">A better way to begin</p><h1 className="mt-3 font-display text-4xl font-extrabold tracking-tight sm:text-6xl">Make your life<br /><span className="text-lime">playable.</span></h1><p className="mx-auto mt-5 max-w-md text-sm leading-7 text-muted">Grindly turns the work you care about into quests, rewards consistency, and makes your progress impossible to ignore.</p><label className="mx-auto mt-8 block max-w-sm text-left"><span className="field-label">What should we call you?</span><input autoFocus value={name} onChange={(event) => setName(event.target.value)} placeholder="Your first name" className="field-input" /></label></div>; }

function AvatarStep({ selected, setSelected, custom, setCustom }) { return <div className="mx-auto max-w-xl"><div className="text-center"><p className="eyebrow text-lime">Step 02 · Identity</p><h1 className="mt-3 font-display text-4xl font-extrabold">Choose your signal.</h1><p className="mt-3 text-sm text-muted">Pick a built-in avatar or bring your own energy.</p></div><div className="mt-8 grid grid-cols-5 gap-2 sm:gap-3">{avatarOptions.map((option) => <button key={option.id} onClick={() => { setSelected(option.id); setCustom(''); }} className={`grid aspect-square place-items-center rounded-2xl border text-3xl transition ${selected === option.id && !custom ? 'border-lime bg-lime/15 ring-1 ring-lime' : 'border-white/10 bg-panel hover:bg-white/8'}`} title={option.name}>{option.emoji}</button>)}</div><div className="mt-5 rounded-2xl border border-dashed border-white/15 bg-panel p-4"><label className="field-label">Custom avatar <span className="text-muted">(emoji or symbol)</span></label><div className="flex gap-3"><input value={custom} onChange={(event) => { setCustom(event.target.value.slice(0, 2)); setSelected(''); }} placeholder="✨" className="field-input" /><div className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-white/5 text-2xl">{custom || '🙂'}</div></div></div></div>; }

function UsernameStep({ username, setUsername }) { return <div className="mx-auto max-w-xl text-center"><div className="mx-auto grid h-16 w-16 place-items-center rounded-3xl border border-lime/30 bg-lime/10 text-lime"><Bot size={29} /></div><p className="eyebrow mt-7 text-lime">Step 03 · Your handle</p><h1 className="mt-3 font-display text-4xl font-extrabold">How will the ranks know you?</h1><p className="mt-3 text-sm text-muted">Choose a name that feels like yours. You can change it later.</p><label className="mx-auto mt-8 block max-w-sm text-left"><span className="field-label">Username</span><input value={username} onChange={(event) => setUsername(event.target.value.replace(/\s/g, '').slice(0, 20))} placeholder="e.g. GrindMaster" className="field-input" /><span className="mt-2 block text-xs text-muted">{username.length}/20 characters · no spaces</span></label></div>; }

function GuideStep() { return <div className="mx-auto max-w-xl"><div className="text-center"><p className="eyebrow text-lime">Step 04 · Meet your co-pilot</p><h1 className="mt-3 font-display text-4xl font-extrabold">You don’t have to<br /><span className="text-lime">figure it out alone.</span></h1></div><div className="mt-8 rounded-3xl border border-lime/20 bg-gradient-to-br from-[#1d2d20] to-panel p-6 sm:p-8"><div className="flex items-center gap-3"><div className="bot-orb"><Bot size={22} /></div><div><p className="font-display text-lg font-bold">Grindly</p><p className="text-xs text-muted">Your momentum co-pilot</p></div></div><p className="mt-7 text-lg leading-8 text-slate-200">“Tell me what’s on your plate in plain language. I’ll help turn it into a clear quest, then the reward engine makes sure the reward stays fair.”</p><div className="mt-6 flex flex-wrap gap-2"><span className="chip-button">Clarify tasks</span><span className="chip-button">Explain rewards</span><span className="chip-button">Keep you moving</span></div></div></div>; }

function TutorialStep() { return <div className="mx-auto max-w-xl"><div className="text-center"><p className="eyebrow text-lime">Step 05 · Your first loop</p><h1 className="mt-3 font-display text-4xl font-extrabold">Small work.<br /><span className="text-lime">Visible progress.</span></h1><p className="mt-3 text-sm text-muted">The whole point is simple: show up, get credit, come back tomorrow.</p></div><div className="mt-8 space-y-3">{[['01', 'Name the real task', 'No productivity theatre. Start with something you actually need to do.'], ['02', 'Clear the quest', 'Completion earns XP, coins, attribute progress, and a satisfying little moment.'], ['03', 'Build the streak', 'Consistency unlocks the best version of Grindly.']].map(([number, title, text]) => <div key={number} className="flex gap-4 rounded-2xl border border-white/10 bg-panel p-4"><span className="font-mono text-xs text-lime">{number}</span><div><p className="font-bold">{title}</p><p className="mt-1 text-sm leading-6 text-muted">{text}</p></div><Check size={16} className="ml-auto mt-1 text-lime" /></div>)}</div></div>; }
