import { motion } from 'framer-motion';
import { CalendarDays, Check, Flame, GitBranch, Medal, Shield, Sparkles, Trophy } from 'lucide-react';
import { Avatar } from '../components/Avatar';
import { XPBar } from '../components/XPBar';
import { LevelDisplay } from '../components/LevelDisplay';

const activityColors = ['bg-white/5', 'bg-lime/15', 'bg-lime/30', 'bg-lime/55', 'bg-lime/85'];
const statLabels = { intelligence: ['Study', 'Coding', 'Learning'], endurance: ['Health', 'Long sessions'], discipline: ['Completed quests', 'Streaks'], creativity: ['Personal', 'Projects'], wisdom: ['Reflection', 'Learning'], social: ['Community', 'Friends'] };

export default function Profile({ user, activity = [], inventory = [] }) {
  const achievements = user.achievements || [];
  const attributes = Object.entries(user.attributes || {});
  const joinDate = user.joinedDate ? new Date(user.joinedDate) : null;
  const activityMap = activity.reduce((map, entry) => { const key = entry.date || entry.completedAt || entry.createdAt; if (key) { const date = new Date(key).toISOString().slice(0, 10); map[date] = (map[date] || 0) + 1; } return map; }, {});
  const today = new Date();
  const cells = Array.from({ length: 365 }, (_, index) => { const date = new Date(today); date.setDate(today.getDate() - (364 - index)); const key = date.toISOString().slice(0, 10); return { key, date, count: activityMap[key] || 0 }; });
  const activeDays = new Set(Object.keys(activityMap)).size;
  return <div className="min-h-screen bg-ink"><div className="mx-auto max-w-6xl px-5 py-7 sm:px-8 lg:px-12 lg:py-10">
    <header className="flex flex-col justify-between gap-6 border-b border-white/8 pb-8 sm:flex-row sm:items-end"><div><p className="eyebrow text-lime">Character sheet</p><h1 className="mt-2 font-display text-4xl font-extrabold">This is your Grindly.</h1><p className="mt-2 max-w-lg text-sm leading-6 text-muted">A living record of your character: what you practice, what you unlock, and how consistently you return.</p></div><button className="btn-secondary flex items-center gap-2 self-start sm:self-auto"><GitBranch size={15} /> Share character</button></header>
    <section className="mt-8 grid gap-5 lg:grid-cols-[1.25fr_.75fr]"><div className="rounded-3xl border border-lime/25 bg-gradient-to-br from-[#17251c] to-panel p-6 sm:p-8"><div className="flex flex-col gap-6 sm:flex-row sm:items-center"><div className="relative"><Avatar avatar={user.avatar} size="xl" /><span className="absolute -bottom-2 -right-2 grid h-8 w-8 place-items-center rounded-xl border border-lime/40 bg-ink text-xs font-extrabold text-lime">{user.level}</span></div><div className="flex-1"><p className="eyebrow text-lime">PLAYER · PATHFINDER</p><h2 className="mt-2 font-display text-3xl font-extrabold">{user.displayName}</h2><p className="mt-1 text-sm text-muted">@{user.username}{joinDate ? ` · Joined ${joinDate.toLocaleDateString(undefined, { month: 'short', year: 'numeric' })}` : ''}</p><div className="mt-6"><XPBar current={user.experience} max={user.nextLevelExp} /></div></div><LevelDisplay level={user.level} size="sm" /></div><div className="mt-8 grid grid-cols-3 gap-3 border-t border-white/10 pt-6"><CharacterMetric label="Streak" value={`${user.streak}d`} icon={Flame} color="text-[#ff9a7e]" /><CharacterMetric label="Rank" value={`#${user.globalRank}`} icon={Trophy} color="text-lime" /><CharacterMetric label="Active days" value={activeDays} icon={CalendarDays} color="text-[#8fd9ff]" /></div></div><div className="rounded-3xl border border-white/10 bg-panel p-6"><p className="eyebrow">Equipped loadout</p><h2 className="mt-2 font-display text-xl font-bold">How you show up</h2>{inventory.filter((item) => item.equipped).length ? inventory.filter((item) => item.equipped).map((item) => <div key={item.id} className="mt-4 flex items-center gap-4"><div className="grid h-14 w-14 place-items-center rounded-2xl border border-lime/40 bg-lime/10 text-lime"><Shield size={25} /></div><div><p className="text-sm font-bold">{item.name}</p><p className="mt-1 text-xs text-muted">{item.category} · Equipped</p></div></div>) : <><div className="mt-6 flex items-center gap-4"><div className="grid h-14 w-14 place-items-center rounded-2xl border border-lime/40 bg-lime/10 text-lime"><Shield size={25} /></div><div><p className="text-sm font-bold">No cosmetics equipped</p><p className="mt-1 text-xs text-muted">Visit the Vault to build your identity.</p></div></div><div className="mt-4 flex items-center gap-4"><div className="grid h-14 w-14 place-items-center rounded-2xl border border-[#ffd27a]/40 bg-[#ffd27a]/10 text-[#ffd27a]"><Sparkles size={25} /></div><div><p className="text-sm font-bold">Default signal</p><p className="mt-1 text-xs text-muted">Your reward effect is ready to evolve.</p></div></div></>}</div></section>
    <section className="mt-10"><div className="mb-4 flex items-end justify-between"><div><p className="eyebrow">Character stats</p><h2 className="mt-2 font-display text-2xl font-extrabold">Attributes</h2></div><p className="text-xs text-muted">Built through the quests you complete</p></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{attributes.map(([name, value], index) => <Attribute key={name} name={name} value={value} index={index} />)}</div></section>
    <section className="mt-10 grid gap-8 lg:grid-cols-[1.35fr_.65fr]"><div><div className="mb-4"><p className="eyebrow">365-day record</p><h2 className="mt-2 font-display text-2xl font-extrabold">Activity field</h2></div><div className="rounded-2xl border border-white/10 bg-panel p-4"><div className="grid grid-cols-[repeat(53,minmax(0,1fr))] grid-rows-7 gap-1">{cells.map(({ key, date, count }) => <div key={key} title={`${date.toLocaleDateString()} · ${count} recorded quest${count === 1 ? '' : 's'}`} className={`aspect-square rounded-[3px] transition hover:ring-2 hover:ring-lime/60 ${activityColors[Math.min(4, count)]}`} />)}</div><div className="mt-4 flex items-center justify-between text-[.65rem] text-muted"><span>{cells[0].date.toLocaleDateString('en-US', { month: 'short' })}</span><span className="flex items-center gap-1.5">Less {activityColors.map((color) => <i key={color} className={`h-2.5 w-2.5 rounded-[2px] ${color}`} />)} More</span></div></div></div><div><div className="mb-4"><p className="eyebrow">Unlocked identity</p><h2 className="mt-2 font-display text-2xl font-extrabold">Achievements</h2></div><div className="space-y-3">{achievements.length ? achievements.map((achievement) => <div key={achievement.id} className="flex items-center gap-3 rounded-2xl border border-white/10 bg-panel p-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#ffd27a]/10 text-[#ffd27a]"><Medal size={19} /></div><div className="min-w-0"><p className="truncate text-sm font-bold">{achievement.name}</p><p className="mt-1 truncate text-xs text-muted">{achievement.description}</p></div><Check size={15} className="ml-auto shrink-0 text-[#8ff0b6]" /></div>) : <p className="rounded-2xl border border-dashed border-white/10 p-5 text-sm text-muted">Your next achievement is waiting in the Journey.</p>}</div></div></section>
  </div></div>;
}

function Attribute({ name, value, index }) {
  const normalized = name.toLowerCase();
  const builtThrough = statLabels[normalized] || ['Completed quests', 'Focused sessions'];
  return <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * .05 }} className="character-stat"><div className="flex items-end justify-between"><div><p className="eyebrow">{name}</p><p className="mt-2 font-display text-3xl font-extrabold text-white">{value}</p></div><span className="font-mono text-xs text-muted">/ 100</span></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-white/8"><motion.div initial={{ width: 0 }} animate={{ width: `${value}%` }} transition={{ duration: .8 }} className="h-full rounded-full bg-gradient-to-r from-lime to-[#7ead43]" /></div><p className="mt-4 text-[.65rem] text-muted">Built through: <span className="text-slate-300">{builtThrough.join(' · ')}</span></p></motion.div>;
}

function CharacterMetric({ label, value, icon: Icon, color }) { return <div className="flex items-center gap-2"><Icon size={16} className={color} /><div><p className="font-display font-bold">{value}</p><p className="text-[.62rem] text-muted">{label}</p></div></div>; }
