import { motion } from 'framer-motion';
import { CalendarDays, Check, Flame, GitBranch, Medal, Sparkles, Trophy } from 'lucide-react';
import { Avatar } from '../components/Avatar';
import { XPBar } from '../components/XPBar';
import { LevelDisplay } from '../components/LevelDisplay';

const activityColors = ['bg-white/5', 'bg-lime/15', 'bg-lime/30', 'bg-lime/55', 'bg-lime/85'];

export default function Profile({ user, activity = [] }) {
  const joinDate = new Date(user.joinedDate);
  const daysActive = Math.max(1, Math.floor((Date.now() - joinDate.getTime()) / 86400000));
  const attributes = Object.entries(user.attributes || {}).map(([name, value]) => ({ name: name.replace(/^./, (letter) => letter.toUpperCase()), value, max: 100 }));
  const achievements = user.achievements || [];
  return <div className="min-h-screen bg-ink"><div className="mx-auto max-w-6xl px-5 py-7 sm:px-8 lg:px-12 lg:py-10">
    <header className="flex flex-col justify-between gap-6 border-b border-white/8 pb-8 sm:flex-row sm:items-end"><div><p className="eyebrow">Player profile</p><h1 className="mt-2 font-display text-4xl font-extrabold">Your progress, in public.</h1><p className="mt-2 max-w-lg text-sm leading-6 text-muted">A record of the work you chose to show up for. Every small square is a day you moved.</p></div><button className="btn-secondary flex items-center gap-2 self-start sm:self-auto"><GitBranch size={15} /> Share profile</button></header>
    <section className="mt-8 grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><div className="rounded-3xl border border-white/10 bg-gradient-to-br from-[#17251c] to-panel p-6 sm:p-8"><div className="flex flex-col gap-6 sm:flex-row sm:items-center"><Avatar avatar={user.avatar} size="xl" /><div className="flex-1"><p className="eyebrow text-lime">Level {user.level} Pathfinder</p><h2 className="mt-2 font-display text-3xl font-extrabold">{user.displayName}</h2><p className="mt-1 text-sm text-muted">@{user.username} · Joined {joinDate.toLocaleDateString('en-US', { month: 'short', year: 'numeric' })}</p><div className="mt-6"><XPBar current={user.experience} max={user.nextLevelExp} /></div></div><LevelDisplay level={user.level} size="sm" /></div><div className="mt-8 grid grid-cols-3 gap-3 border-t border-white/10 pt-6"><Metric label="Streak" value={`${user.streak}d`} icon={Flame} color="text-[#ff9a7e]" /><Metric label="Global rank" value={`#${user.globalRank}`} icon={Trophy} color="text-lime" /><Metric label="Days active" value={daysActive} icon={CalendarDays} color="text-[#8fd9ff]" /></div></div><div className="rounded-3xl border border-white/10 bg-panel p-6"><div className="flex items-center justify-between"><div><p className="eyebrow">Recent activity</p><h2 className="mt-2 font-display text-xl font-bold">Momentum log</h2></div><Sparkles size={18} className="text-lime" /></div><div className="mt-5 space-y-4">{activity.slice(0, 4).map((item) => <div key={item.id} className="flex gap-3"><div className="mt-1 grid h-7 w-7 shrink-0 place-items-center rounded-lg bg-lime/10 text-lime"><Check size={14} /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-slate-200">{item.title}</p><p className="mt-1 text-xs text-muted">{item.detail}</p></div><span className="shrink-0 text-[.65rem] text-muted">{item.time}</span></div>)}</div></div></section>
    <section className="mt-8"><div className="mb-4 flex items-end justify-between"><div><p className="eyebrow">Character sheet</p><h2 className="mt-2 font-display text-2xl font-extrabold">Core attributes</h2></div><p className="text-xs text-muted">Built by what you practice</p></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{attributes.map((attribute, index) => <motion.div key={attribute.name} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * .05 }} className="rounded-2xl border border-white/10 bg-panel p-4"><div className="flex items-center justify-between"><span className="text-sm font-semibold">{attribute.name}</span><span className="font-mono text-xs text-lime">{attribute.value}<span className="text-muted">/{attribute.max}</span></span></div><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-white/8"><motion.div initial={{ width: 0 }} animate={{ width: `${attribute.value}%` }} transition={{ duration: .8 }} className="h-full rounded-full bg-gradient-to-r from-lime to-[#7ead43]" /></div><p className="mt-3 text-xs text-muted">Live from completed quests</p></motion.div>)}</div></section>
    <section className="mt-8 grid gap-8 lg:grid-cols-[1.3fr_.7fr]"><div><div className="mb-4"><p className="eyebrow">Last 365 days</p><h2 className="mt-2 font-display text-2xl font-extrabold">Activity field</h2></div><div className="rounded-2xl border border-white/10 bg-panel p-4"><div className="grid grid-cols-[repeat(26,minmax(0,1fr))] gap-1">{Array.from({ length: 182 }, (_, index) => { const date = new Date(); date.setDate(date.getDate() - (181 - index)); const intensity = Math.floor(Math.abs(Math.sin(index * .71) * 4.2)); return <div key={date.toISOString()} title={`${date.toLocaleDateString()} · ${intensity} focus sessions`} className={`aspect-square rounded-[3px] transition hover:ring-2 hover:ring-lime/60 ${activityColors[intensity]}`} />; })}</div><div className="mt-4 flex items-center justify-between text-[.65rem] text-muted"><span>6 months ago</span><span className="flex items-center gap-1.5">Less {activityColors.slice(0, 5).map((color) => <i key={color} className={`h-2.5 w-2.5 rounded-[2px] ${color}`} />)} More</span></div></div></div><div><div className="mb-4"><p className="eyebrow">Milestones</p><h2 className="mt-2 font-display text-2xl font-extrabold">Achievements</h2></div><div className="space-y-3">{achievements.length ? achievements.map((achievement) => <div key={achievement.id} className="flex items-center gap-3 rounded-2xl border border-white/10 bg-panel p-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#ffd27a]/10 text-[#ffd27a]"><Medal size={19} /></div><div className="min-w-0"><p className="truncate text-sm font-bold">{achievement.name}</p><p className="mt-1 truncate text-xs text-muted">{achievement.description}</p></div><Medal size={15} className="ml-auto shrink-0 text-[#ffd27a]" /></div>) : <p className="rounded-2xl border border-dashed border-white/10 p-5 text-sm text-muted">Your next milestone will appear here.</p>}</div></div></section>
  </div></div>;
}

function Metric({ label, value, icon: Icon, color }) { return <div className="flex items-center gap-2"><Icon size={16} className={color} /><div><p className="font-display font-bold">{value}</p><p className="text-[.62rem] text-muted">{label}</p></div></div>; }
