import { useState } from 'react';
import { motion } from 'framer-motion';
import { Award, Castle, Check, Crown, Gift, Lock, Swords, Target, Trophy, Users, Zap } from 'lucide-react';
import { XPBar } from '../components/XPBar';

const classes = [
  { name: 'Scholar', icon: '✦', bonus: '+10% Study XP', detail: 'Turn learning quests into a path of mastery.', color: 'blue' },
  { name: 'Forger', icon: '⚒', bonus: '+10% Coding XP', detail: 'Build momentum through difficult work.', color: 'orange' },
  { name: 'Guardian', icon: '◈', bonus: '+1 streak shield', detail: 'Protect your run when the day slips.', color: 'lime' },
  { name: 'Wanderer', icon: '⌁', bonus: '+10% discovery drops', detail: 'Find secret achievements and rare relics.', color: 'violet' },
];
const chapters = [
  { title: 'The First Signal', detail: 'Complete your first focused quest.', progress: 1, goal: 1, boss: 'The Blank Page', reward: 'Starter relic' },
  { title: 'City of Momentum', detail: 'Build a seven-day streak.', progress: 3, goal: 7, boss: 'The Interruptor', reward: 'Knight companion' },
  { title: 'The Long Game', detail: 'Reach level 10 and complete 25 quests.', progress: 4, goal: 10, boss: 'The Old Pattern', reward: 'Legendary loadout' },
];
const skills = [
  { name: 'Quest Sense', detail: 'Create clearer, more finishable quests.', cost: 1, icon: Target },
  { name: 'Focus Shield', detail: 'Protect one missed day each season.', cost: 2, icon: Castle },
  { name: 'Critical Finish', detail: 'Unlock rare reward moments on hard quests.', cost: 3, icon: Swords },
];

export default function Progression({ user }) {
  const [selectedClass, setSelectedClass] = useState(classes[0].name);
  const [claimed, setClaimed] = useState(false);
  const [skillPoints, setSkillPoints] = useState(3);
  const [seasonTab, setSeasonTab] = useState('pass');
  const currentClass = classes.find((item) => item.name === selectedClass);
  return <div className="rpg-page min-h-screen bg-ink"><div className="mx-auto max-w-7xl px-5 py-8 sm:px-8 lg:px-12 lg:py-10">
    <header className="rpg-header"><div><p className="eyebrow text-lime">RPG command center · season 01</p><h1 className="mt-2 font-display text-4xl font-extrabold sm:text-5xl">Your legend is loading.</h1><p className="mt-3 max-w-2xl text-sm leading-7 text-muted">Choose a build, advance your campaign, unlock skills, and turn every focused session into a visible part of your character.</p></div><div className="rpg-level-orb"><Crown size={20} /><span><small>PLAYER LEVEL</small><strong>{user.level}</strong></span></div></header>
    <section className="rpg-hero-grid mt-7"><div className="rpg-level-panel"><div className="flex items-start justify-between gap-4"><div><p className="eyebrow text-lime">Current character</p><h2 className="mt-2 font-display text-3xl font-extrabold">Level {user.level} Pathfinder</h2><p className="mt-1 text-sm text-muted">{currentClass.name} build · {currentClass.bonus}</p></div><div className="rpg-rank-medal">{currentClass.icon}</div></div><div className="mt-6"><div className="flex justify-between text-xs text-muted"><span>{user.experience.toLocaleString()} XP</span><span>{user.nextLevelExp.toLocaleString()} XP to level {user.level + 1}</span></div><div className="mt-2"><XPBar current={user.experience} max={user.nextLevelExp} /></div></div><div className="rpg-stat-row"><span><small>STREAK</small><strong>{user.streak} days</strong></span><span><small>SKILL POINTS</small><strong>{skillPoints}</strong></span><span><small>SEASON RANK</small><strong>#{user.globalRank}</strong></span></div></div><div className="rpg-boss-card"><div className="rpg-boss-sigil"><Swords size={29} /></div><p className="eyebrow text-[#ffab91]">Weekly boss quest</p><h2 className="mt-2 font-display text-2xl font-extrabold">The Interruptor</h2><p className="mt-2 text-sm leading-6 text-muted">Complete 5 focused quests this week to break its cycle.</p><div className="mt-5 flex items-center justify-between text-xs"><span className="text-muted">2 / 5 quests</span><span className="font-bold text-[#ffab91]">Reward: rare chest</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-black/30"><div className="h-full w-2/5 rounded-full bg-[#ff896d]" /></div></div></section>
    <RpgSection title="Choose your class" eyebrow="Character build" icon={Users}><div className="class-grid">{classes.map((item) => <button key={item.name} onClick={() => setSelectedClass(item.name)} className={`class-card class-card-${item.color} ${selectedClass === item.name ? 'class-card-active' : ''}`}><span className="class-glyph">{item.icon}</span><span><strong>{item.name}</strong><small>{item.bonus}</small><em>{item.detail}</em></span>{selectedClass === item.name && <Check size={16} className="class-check" />}</button>)}</div></RpgSection>
    <RpgSection title="Campaign chapters" eyebrow="Story mode" icon={Swords}><div className="chapter-grid">{chapters.map((chapter, index) => <article key={chapter.title} className={`chapter-card ${index === 1 ? 'chapter-card-active' : ''}`}><div className="chapter-art"><span>0{index + 1}</span><div className="chapter-glyph">{index === 0 ? '✦' : index === 1 ? '⚔' : '♜'}</div></div><div className="p-4"><p className="eyebrow">Chapter {index + 1}</p><h3 className="mt-1 font-display text-lg font-bold">{chapter.title}</h3><p className="mt-2 text-xs leading-5 text-muted">{chapter.detail}</p><div className="mt-4 flex justify-between text-[.65rem] text-muted"><span>{chapter.progress} / {chapter.goal}</span><span>{chapter.boss}</span></div><div className="mt-2 h-1.5 rounded-full bg-white/10"><div className="h-full rounded-full bg-lime" style={{ width: `${Math.min(100, chapter.progress / chapter.goal * 100)}%` }} /></div><p className="mt-3 flex items-center gap-1.5 text-xs font-bold text-lime"><Gift size={13} /> {chapter.reward}</p></div></article>)}</div></RpgSection>
    <div className="rpg-two-column"><RpgSection title="Skill tree" eyebrow="Spend your points" icon={Zap}><div className="skill-tree">{skills.map((skill) => { const Icon = skill.icon; const locked = skillPoints < skill.cost; return <button key={skill.name} disabled={locked} onClick={() => setSkillPoints((points) => points - skill.cost)} className={`skill-node ${locked ? 'skill-node-locked' : ''}`}><div className="skill-node-icon"><Icon size={17} /></div><span><strong>{skill.name}</strong><small>{skill.detail}</small><em>{locked ? `${skill.cost} points needed` : `Unlock · ${skill.cost} SP`}</em></span></button>; })}</div></RpgSection><RpgSection title="Loadout slots" eyebrow="Inventory stats" icon={Award}><div className="equipment-grid">{['Weapon · Focus', 'Armor · Routine', 'Relic · Identity', 'Companion · Grindly'].map((slot, index) => <div key={slot} className="equipment-slot"><span>{index === 0 ? '⚔' : index === 1 ? '◈' : index === 2 ? '✧' : '●'}</span><small>{slot.split(' · ')[0]}</small><strong>{slot.split(' · ')[1]}</strong><em>{index < 2 ? 'Empty slot' : 'Equipped'}</em></div>)}</div></RpgSection></div>
    <RpgSection title="Season zero · The First Run" eyebrow="Battle pass & leaderboard" icon={Trophy}><div className="season-tabs"><button onClick={() => setSeasonTab('pass')} className={seasonTab === 'pass' ? 'active' : ''}>Reward track</button><button onClick={() => setSeasonTab('guild')} className={seasonTab === 'guild' ? 'active' : ''}>Guild raid</button><button onClick={() => setSeasonTab('rank')} className={seasonTab === 'rank' ? 'active' : ''}>Season rank</button></div>{seasonTab === 'pass' && <div className="battle-pass"><div className="battle-pass-track"><span className="battle-pass-progress" /></div><div className="battle-pass-rewards">{['Coin pouch', 'XP burst', 'Rare frame', 'Season crown'].map((reward, index) => <div key={reward} className={index < 2 ? 'claimed' : ''}><span>{index < 2 ? '✓' : '◆'}</span><small>Tier {index + 1}</small><strong>{reward}</strong></div>)}</div></div>}{seasonTab === 'guild' && <div className="guild-panel"><div><p className="eyebrow text-lime">Guild raid · shared objective</p><h3 className="mt-2 font-display text-xl font-bold">Light the Beacon</h3><p className="mt-1 text-sm text-muted">Your guild needs 42 more completed quests before reset.</p></div><div className="guild-progress"><strong>68%</strong><div><span /></div><small>68 / 100 quests</small></div></div>}{seasonTab === 'rank' && <div className="season-rank-list">{['NovaPilot', 'QuietBuilder', user.username || 'You', 'SignalForge'].map((name, index) => <div key={name}><span>0{index + 1}</span><strong>{name}</strong><small>{(1240 - index * 118).toLocaleString()} RP</small></div>)}</div>}</RpgSection>
    <div className="rpg-two-column"><RpgSection title="Daily quest board" eyebrow="Fresh objectives" icon={Target}><div className="quest-board">{['Finish one focused quest', 'Protect your streak', 'Visit the Reliquary'].map((quest, index) => <div key={quest}><span className={index === 0 ? 'quest-board-active' : ''}>{index === 0 ? '!' : '·'}</span><strong>{quest}</strong><small>+{(index + 1) * 40} XP</small></div>)}</div></RpgSection><RpgSection title="Chest room" eyebrow="Open your drops" icon={Gift}><div className="chest-room"><div className="chest-visual">{claimed ? '✦' : '▣'}</div><div><h3 className="font-display font-bold">{claimed ? 'Chest opened' : 'Focus chest ready'}</h3><p className="mt-1 text-xs leading-5 text-muted">{claimed ? 'A reward was added to your collection.' : 'Complete one more quest to reveal a random relic.'}</p><button disabled={claimed} onClick={() => setClaimed(true)} className="btn-primary mt-3 flex items-center gap-2 text-xs disabled:opacity-50"><Lock size={13} /> {claimed ? 'Claimed' : 'Open chest'}</button></div></div></RpgSection></div>
  </div></div>;
}

function RpgSection({ title, eyebrow, icon: Icon, children }) { return <section className="rpg-section"><div className="rpg-section-heading"><div className="rpg-section-icon"><Icon size={17} /></div><div><p className="eyebrow text-lime">{eyebrow}</p><h2 className="mt-1 font-display text-2xl font-extrabold">{title}</h2></div></div>{children}</section>; }