import { useState } from 'react';
import { Bell, Check, ChevronRight, Eye, Moon, Palette, Shield, Sun, UserRound, Volume2, Zap } from 'lucide-react';

const preferenceGroups = [
  { title: 'Experience', rows: [{ id: 'animations', label: 'Animations', detail: 'Reward reveals, journey motion, and character idle states', icon: Zap }, { id: 'sound', label: 'Sound effects', detail: 'Tactile feedback for quest starts and unlocks', icon: Volume2 }] },
  { title: 'Notifications', rows: [{ id: 'quest-reminders', label: 'Quest reminders', detail: 'A nudge when your active session is waiting', icon: Bell }, { id: 'reward-notifications', label: 'Reward notifications', detail: 'Celebrate level-ups and new unlocks', icon: SparkIcon }, { id: 'friend-activity', label: 'Friend activity', detail: 'See when your circle reaches a milestone', icon: UserRound }] },
  { title: 'Privacy', rows: [{ id: 'profile-visibility', label: 'Profile visibility', detail: 'Let other players see your character sheet', icon: Eye }, { id: 'activity-visibility', label: 'Activity visibility', detail: 'Show your contribution field on your profile', icon: Eye }, { id: 'friend-controls', label: 'Friend controls', detail: 'Manage who can follow your progress', icon: Shield }] },
];

export default function SettingsPage({ theme, onThemeChange }) {
  const [preferences, setPreferences] = useState(() => Object.fromEntries(preferenceGroups.flatMap((group) => group.rows).map((row) => [row.id, window.localStorage.getItem(`grindly-${row.id}`) !== 'off'])));
  const toggle = (id) => setPreferences((current) => { const next = { ...current, [id]: !current[id] }; window.localStorage.setItem(`grindly-${id}`, next[id] ? 'on' : 'off'); return next; });
  return <div className="min-h-screen bg-ink"><div className="mx-auto max-w-3xl px-5 py-8 sm:px-8 lg:px-12 lg:py-10"><header className="border-b border-white/8 pb-8"><p className="eyebrow text-lime">Game settings</p><h1 className="mt-2 font-display text-4xl font-extrabold">Tune your run.</h1><p className="mt-2 text-sm leading-6 text-muted">Make Grindly fit your focus without changing the rules of the game.</p></header>
    <section className="mt-8"><p className="eyebrow">Appearance</p><div className="mt-3 grid gap-3 sm:grid-cols-2"><ThemeButton active={theme === 'dark'} icon={Moon} label="Dark mode" detail="Deep contrast for late sessions" onClick={() => onThemeChange('dark')} /><ThemeButton active={theme === 'light'} icon={Sun} label="Light mode" detail="Bright contrast for daytime runs" onClick={() => onThemeChange('light')} /></div></section>
    {preferenceGroups.map((group) => <section key={group.title} className="mt-8"><p className="eyebrow">{group.title}</p><div className="card mt-3 divide-y divide-white/8 p-0">{group.rows.map(({ id, label, detail, icon: Icon }) => <div key={id} className="flex items-center gap-4 p-4"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-lime/10 text-lime"><Icon size={18} /></div><div className="min-w-0 flex-1"><p className="text-sm font-bold">{label}</p><p className="mt-1 text-xs text-muted">{detail}</p></div><button onClick={() => toggle(id)} aria-pressed={preferences[id]} className={`relative h-6 w-11 rounded-full transition ${preferences[id] ? 'bg-lime' : 'bg-white/15'}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white transition ${preferences[id] ? 'left-6' : 'left-1'}`} /></button></div>)}</div></section>)}
    <section className="mt-8"><p className="eyebrow">Account & legal</p><div className="card mt-3 divide-y divide-white/8 p-0">{[['Account settings', 'Update your identity and sign-in details', UserRound], ['Terms & Conditions', 'The rules of the journey', Shield], ['Privacy Policy', 'How Grindly handles your data', Shield], ['Community guidelines', 'Keep the grind respectful', Palette]].map(([label, detail, Icon]) => <button key={label} className="flex w-full items-center gap-4 p-4 text-left transition hover:bg-white/[.03]"><Icon size={18} className="text-muted" /><span className="min-w-0 flex-1"><span className="block text-sm font-bold">{label}</span><span className="mt-1 block text-xs text-muted">{detail}</span></span><ChevronRight size={16} className="text-muted" /></button>)}</div></section>
  </div></div>;
}

function ThemeButton({ active, icon: Icon, label, detail, onClick }) { return <button onClick={onClick} className={`flex items-center gap-3 rounded-2xl border p-4 text-left transition ${active ? 'border-lime/40 bg-lime/10' : 'border-white/10 bg-panel hover:border-lime/25'}`}><Icon size={18} className={active ? 'text-lime' : 'text-muted'} /><span className="flex-1"><span className="block text-sm font-bold">{label}</span><span className="mt-1 block text-xs text-muted">{detail}</span></span>{active && <Check size={16} className="text-lime" />}</button>; }
function SparkIcon(props) { return <Palette {...props} />; }
