import { useEffect, useRef, useState } from 'react';
import { Bell, Check, ChevronRight, Eye, FileText, Moon, Palette, Shield, Sun, UserRound, Volume2, Zap, AlertTriangle } from 'lucide-react';
import { avatarOptions } from '../data/mockData';
import { Avatar } from '../components/Avatar';

const preferenceGroups = [
  { title: 'Experience', rows: [{ id: 'animations', label: 'Animations', detail: 'Reward reveals and character motion', icon: Zap }, { id: 'sound', label: 'Sound effects', detail: 'Gameplay and reward feedback', icon: Volume2 }] },
  { title: 'Notifications', rows: [{ id: 'quest_reminders', label: 'Quest reminders', detail: 'A nudge when a focused session is waiting', icon: Bell }, { id: 'reward_notifications', label: 'Reward notifications', detail: 'Level-ups and new unlocks', icon: Bell }, { id: 'friend_activity', label: 'Friend activity', detail: 'Milestones from your circle', icon: UserRound }] },
  { title: 'Privacy', rows: [{ id: 'profile_visibility', label: 'Profile visibility', detail: 'Control who can inspect your character', icon: Eye, select: true }, { id: 'activity_visibility', label: 'Activity visibility', detail: 'Control who can see your activity field', icon: Eye, select: true }] },
];

export default function SettingsPage({ user, theme, onThemeChange, preferences = {}, onPreferencesChange, onAvatarChange, onUpdateAccount, onSignOut, onDeleteAccount }) {
  const [document, setDocument] = useState(null);
  const [local, setLocal] = useState(preferences);
  const [account, setAccount] = useState({ displayName: user?.displayName || '', username: user?.username || '' });
  const [accountError, setAccountError] = useState('');
  useEffect(() => setLocal(preferences), [preferences]);
  const update = (id, value) => { const next = { ...local, [id]: value }; setLocal(next); onPreferencesChange(next); };
  const docs = {
    account: ['Account settings', 'Manage your public identity and account lifecycle.', []],
    terms: ['Terms & Conditions', 'The rules of the journey.', ['Effective date: September 12, 2026.', 'Grindly is a productivity game. You are responsible for the quests you create and the time you spend on them.', 'Do not manipulate timers, rewards, rankings, friend systems, or app telemetry. Do not use automation, scraping, exploits, or multiple accounts to gain an unfair advantage.', 'Cosmetics, XP, coins, achievements, and rankings are virtual game data. They have no cash value and may be adjusted to correct abuse, bugs, or balance issues.', 'You keep ownership of content you submit, but grant Grindly permission to process it to operate the service. Do not submit unlawful, hateful, harassing, sexually explicit, or infringing content.', 'We may suspend or delete accounts that abuse the service, threaten others, evade safeguards, or violate these terms. We may change features and these terms with notice in the product.', 'Use of Grindly means you accept these terms and agree to use the service responsibly.']],
    privacy: ['Privacy Policy', 'How Grindly handles your data.', ['Effective date: September 12, 2026.', 'Grindly stores your Firebase identifier, email when supplied, username, display name, avatar, quests, timed sessions, rewards, activity history, preferences, inventory, notifications, AI requests, and friendship records.', 'We use this information to authenticate you, save progression, calculate rewards, show your profile according to your visibility settings, operate social features, prevent abuse, and improve reliability.', 'Your public profile may show your username, display name, avatar, level, XP, streak, achievements, equipped cosmetics, and friend count depending on your settings. Private information is not intentionally published through the app.', 'We do not sell your personal data. Authentication is provided by Firebase. Configure your profile and activity visibility before connecting with other players.', 'You may edit your identity, sign out, or permanently delete your account. Deletion removes your Grindly records and cannot be undone. Contact the project owner for privacy questions or data requests.']],
    community: ['Community Guidelines', 'Keep the grind respectful and safe.', ['Be respectful. No harassment, bullying, hate speech, threats, discrimination, sexual harassment, or targeted abuse.', 'Do not impersonate another player, expose private information, spam requests, manipulate friendships, or use the app to contact someone who has asked you to stop.', 'Do not cheat. No timer manipulation, reward exploits, ranking manipulation, bots, scraping, account farming, or attempts to bypass access controls.', 'Keep usernames, avatars, quest titles, and messages appropriate for a shared community. Do not upload illegal, hateful, violent, sexually explicit, or copyrighted material you do not have permission to use.', 'Report unsafe behavior to the project owner with enough context to investigate. We may remove content, restrict social access, suspend, or delete accounts that violate these guidelines.']],
  };
  if (document) return <DocumentPage document={docs[document]} account={account} setAccount={setAccount} accountError={accountError} setAccountError={setAccountError} onUpdateAccount={onUpdateAccount} onDeleteAccount={onDeleteAccount} onBack={() => setDocument(null)} onSignOut={onSignOut} onAccept={() => update(`${document}_accepted_at`, new Date().toISOString())} accepted={Boolean(local[`${document}_accepted_at`])} />;
  return <div className="min-h-screen bg-ink"><div className="mx-auto max-w-3xl px-5 py-8 sm:px-8 lg:px-12 lg:py-10"><header className="border-b border-white/8 pb-8"><p className="eyebrow text-lime">Game settings</p><h1 className="mt-2 font-display text-4xl font-extrabold">Tune your run.</h1><p className="mt-2 text-sm leading-6 text-muted">These preferences are saved to your Grindly account.</p></header>
    <AvatarSettings user={user} onAvatarChange={onAvatarChange} />
    <section className="mt-8"><p className="eyebrow">Appearance</p><div className="mt-3 grid gap-3 sm:grid-cols-3"><ThemeButton active={theme === 'dark'} icon={Moon} label="Dark" onClick={() => onThemeChange('dark')} /><ThemeButton active={theme === 'light'} icon={Sun} label="Light" onClick={() => onThemeChange('light')} /><ThemeButton active={theme === 'system'} icon={Palette} label="System" onClick={() => onThemeChange('system')} /></div></section>
    {preferenceGroups.map((group) => <section key={group.title} className="mt-8"><p className="eyebrow">{group.title}</p><div className="card mt-3 divide-y divide-white/8 p-0">{group.rows.map(({ id, label, detail, icon: Icon, select }) => <div key={id} className="flex items-center gap-4 p-4"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-lime/10 text-lime"><Icon size={18} /></div><div className="min-w-0 flex-1"><p className="text-sm font-bold">{label}</p><p className="mt-1 text-xs text-muted">{detail}</p></div>{select ? <select value={local[id] || 'public'} onChange={(event) => update(id, event.target.value)} className="rounded-lg border border-white/10 bg-ink px-2 py-1.5 text-xs text-white"><option value="public">Public</option><option value="friends">Friends</option><option value="private">Private</option></select> : <button onClick={() => update(id, local[id] === false)} aria-pressed={local[id] !== false} className={`relative h-6 w-11 rounded-full transition ${local[id] !== false ? 'bg-lime' : 'bg-white/15'}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white transition ${local[id] !== false ? 'left-6' : 'left-1'}`} /></button>}</div>)}</div></section>)}
    <section className="mt-8"><p className="eyebrow">Account & legal</p><div className="card mt-3 divide-y divide-white/8 p-0">{[['account', 'Account settings', 'Update your identity and sign-in details', UserRound], ['terms', 'Terms & Conditions', 'The rules of the journey', FileText], ['privacy', 'Privacy Policy', 'How Grindly handles your data', Shield], ['community', 'Community guidelines', 'Keep the grind respectful', Shield]].map(([id, label, detail, Icon]) => <button key={id} onClick={() => setDocument(id)} className="flex w-full items-center gap-4 p-4 text-left transition hover:bg-white/[.03]"><Icon size={18} className="text-muted" /><span className="min-w-0 flex-1"><span className="block text-sm font-bold">{label}</span><span className="mt-1 block text-xs text-muted">{detail}</span></span><ChevronRight size={16} className="text-muted" /></button>)}</div></section>
    <button onClick={onSignOut} className="mt-8 w-full rounded-xl border border-rose-400/25 bg-rose-400/10 px-4 py-3 text-sm font-bold text-rose-200">Sign out of Grindly</button>
  </div></div>;
}

function AvatarSettings({ user, onAvatarChange }) {
  const fileInput = useRef(null);
  const [preview, setPreview] = useState(user?.avatar || 'avatar-1');
  const choose = (value) => { setPreview(value); onAvatarChange?.(value); };
  const upload = (event) => {
    const file = event.target.files?.[0];
    if (!file || !file.type.startsWith('image/') || file.size > 350000) return;
    const reader = new FileReader();
    reader.onload = () => choose(reader.result);
    reader.readAsDataURL(file);
  };
  return <section className="mt-8"><p className="eyebrow">Identity</p><div className="card mt-3 p-5"><div className="flex items-center gap-4"><Avatar avatar={preview} size="lg" /><div><p className="font-display text-xl font-bold">Choose your signal</p><p className="mt-1 text-xs text-muted">Changes preview instantly and appear across your profile, navigation, and rankings.</p></div></div><div className="mt-5 grid grid-cols-5 gap-2 sm:grid-cols-10">{avatarOptions.map((option) => <button key={option.id} type="button" title={option.name} aria-label={`Choose ${option.name} avatar`} onClick={() => choose(option.id)} className={`grid aspect-square place-items-center rounded-xl border transition ${preview === option.id ? 'border-lime bg-lime/15 ring-2 ring-lime/20' : 'border-white/10 bg-ink hover:border-lime/40'}`}><Avatar avatar={option.id} size="sm" border={false} /></button>)}</div><div className="mt-4 flex items-center gap-3"><button type="button" onClick={() => fileInput.current?.click()} className="btn-secondary text-xs">Upload custom image</button><span className="text-xs text-muted">JPG, PNG, or WebP · 350 KB max</span><input ref={fileInput} type="file" accept="image/png,image/jpeg,image/webp" onChange={upload} className="hidden" /></div></div></section>;
}

function ThemeButton({ active, icon: Icon, label, onClick }) { return <button onClick={onClick} className={`flex items-center gap-3 rounded-2xl border p-4 text-left transition ${active ? 'border-lime/40 bg-lime/10' : 'border-white/10 bg-panel hover:border-lime/25'}`}><Icon size={18} className={active ? 'text-lime' : 'text-muted'} /><span className="flex-1 text-sm font-bold">{label}</span>{active && <Check size={16} className="text-lime" />}</button>; }
function DocumentPage({ document, account, setAccount, accountError, setAccountError, onUpdateAccount, onDeleteAccount, onBack, onSignOut, onAccept, accepted }) {
  const [title, detail, paragraphs] = document;
  const [confirmDelete, setConfirmDelete] = useState(false);
  const [confirmDeleteAgain, setConfirmDeleteAgain] = useState(false);
  const isAccount = title === 'Account settings';
  const saveAccount = async (event) => {
    event.preventDefault();
    if (!/^[a-zA-Z0-9_]{3,32}$/.test(account.username)) return setAccountError('Username must be 3–32 letters, numbers, or underscores.');
    if (!account.displayName.trim()) return setAccountError('Display name is required.');
    setAccountError('');
    try { await onUpdateAccount(account); } catch (error) { setAccountError(error.message); }
  };
  const deleteAccount = async () => {
    if (!confirmDeleteAgain) { setConfirmDeleteAgain(true); return; }
    await onDeleteAccount();
  };
  return <div className="min-h-screen bg-ink"><div className="mx-auto max-w-2xl px-5 py-10 sm:px-8"><button onClick={onBack} className="btn-secondary">Back to settings</button><p className="eyebrow mt-10 text-lime">Grindly document</p><h1 className="mt-2 font-display text-4xl font-extrabold">{title}</h1><p className="mt-3 text-muted">{detail}</p>{isAccount ? <><form onSubmit={saveAccount} className="card mt-8 space-y-4"><label><span className="field-label">Display name</span><input value={account.displayName} onChange={(event) => setAccount({ ...account, displayName: event.target.value })} className="field-input" /></label><label><span className="field-label">Username</span><input value={account.username} onChange={(event) => setAccount({ ...account, username: event.target.value.replace(/\s/g, '') })} className="field-input" /></label>{accountError && <p className="rounded-xl border border-rose-300/25 bg-rose-400/10 p-3 text-xs text-rose-100">{accountError}</p>}<button className="btn-primary w-full">Save account changes</button></form><div className="card mt-5 border-rose-300/20"><div className="flex items-start gap-3"><AlertTriangle className="mt-0.5 text-rose-200" size={18} /><div><p className="font-bold text-rose-100">Delete account</p><p className="mt-1 text-xs leading-5 text-muted">This permanently deletes your Grindly quests, rewards, inventory, friendships, preferences, and activity.</p></div></div>{!confirmDelete ? <button onClick={() => setConfirmDelete(true)} className="mt-4 w-full rounded-xl border border-rose-300/25 bg-rose-400/10 px-4 py-3 text-sm font-bold text-rose-100">Delete my account</button> : <div className="mt-4 space-y-2"><p className="text-xs font-bold text-rose-100">Are you absolutely sure? This cannot be undone.</p><button onClick={deleteAccount} className="w-full rounded-xl bg-rose-500 px-4 py-3 text-sm font-bold text-white">{confirmDeleteAgain ? 'Click again to permanently delete' : 'Confirm deletion'}</button><button onClick={() => { setConfirmDelete(false); setConfirmDeleteAgain(false); }} className="btn-secondary w-full">Cancel</button></div>}</div><button onClick={onSignOut} className="mt-6 btn-secondary">Sign out</button></> : <><article className="card mt-8 space-y-5 text-sm leading-7 text-slate-300">{paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</article><label className="mt-6 flex items-start gap-3 rounded-2xl border border-lime/20 bg-lime/5 p-4 text-sm text-slate-200"><input type="checkbox" checked={accepted} disabled={accepted} onChange={onAccept} className="mt-1 accent-lime" /> <span>{accepted ? 'You accepted this document. This acknowledgement is saved to your account.' : 'I have read and accept this document.'}</span></label></>}</div></div>;
}
