import { useMemo, useState } from 'react';
import { motion } from 'framer-motion';
import { BadgeCheck, Check, Coins, Crown, Gift, Lock, Orbit, Palette, Sparkles, Shield, ShoppingBag, Star, Trophy, Zap, Gem, X } from 'lucide-react';
import { Avatar } from '../components/Avatar';
import { getRarityColor } from '../data/mockData';
import { playEquip, playVaultPurchase } from '../services/sound';

const categories = ['All', 'Profile Frame', 'Nameplate', 'Theme', 'XP Effect', 'Avatar Effect', 'Badge', 'Trophy Display'];
const rarityStyles = {
  Common: { panel: 'from-slate-700/80 to-slate-950', border: 'border-slate-400/30', glow: '', artifact: 'bg-slate-500/20' },
  Rare: { panel: 'from-sky-500/45 to-slate-950', border: 'border-sky-300/50', glow: 'shadow-[0_0_28px_rgba(56,189,248,.18)]', artifact: 'bg-sky-300/20' },
  Epic: { panel: 'from-violet-500/50 to-slate-950', border: 'border-violet-300/55', glow: 'shadow-[0_0_34px_rgba(167,139,250,.22)]', artifact: 'bg-violet-300/20' },
  Elite: { panel: 'from-rose-500/50 to-slate-950', border: 'border-rose-300/55', glow: 'shadow-[0_0_38px_rgba(251,113,133,.24)]', artifact: 'bg-rose-300/20' },
  Legendary: { panel: 'from-amber-400/60 to-slate-950', border: 'border-amber-200/70', glow: 'shadow-[0_0_44px_rgba(251,191,36,.3)]', artifact: 'bg-amber-200/25' },
  Mythic: { panel: 'from-fuchsia-500/70 via-indigo-900 to-slate-950', border: 'border-fuchsia-200/80', glow: 'shadow-[0_0_58px_rgba(217,70,239,.38)]', artifact: 'bg-fuchsia-200/25' },
};
const frameMaterialColors = {
  wood: '#765239', iron: '#65717b', bronze: '#a9673b', copper: '#dd8a62',
  silver: '#d9e5ed', steel: '#90a4b8', titanium: '#b8c5d8', gold: '#f6c85f',
  'rose-gold': '#f3a5a0', platinum: '#e9f3ff', obsidian: '#596277', pearl: '#f9e9d2',
  sapphire: '#63b5ff', ruby: '#ff6f83', emerald: '#72f0b0', amethyst: '#d2a1ff',
  moonstone: '#9fe9ff', meteor: '#ff9873', crystal: '#e4fcff', diamond: '#f6ffff',
};

export default function Shop({ user, items, onPurchase, onEquip }) {
  const [category, setCategory] = useState('All');
  const [selectedItem, setSelectedItem] = useState(null);
  const filteredItems = useMemo(() => category === 'All' ? items : items.filter((item) => item.category === category), [category, items]);
  return <div className="vault-page min-h-screen bg-ink"><div className="mx-auto max-w-7xl px-5 py-7 sm:px-8 lg:px-12 lg:py-10">
    <header className="vault-header"><div><p className="eyebrow text-lime">Sector 07 · reward vault</p><h1 className="mt-2 font-display text-4xl font-extrabold sm:text-5xl">The Reliquary.</h1><p className="mt-3 max-w-xl text-sm leading-6 text-muted">A living inventory of the identity you are building. Inspect rare artifacts, claim your next upgrade, and curate a loadout worth showing off.</p><div className="vault-status-line"><span className="status-dot" /> VAULT ONLINE <span>·</span> {items.filter((item) => item.owned).length} artifacts bound</div></div><div className="vault-pouch"><div className="vault-pouch-icon"><Coins size={19} /></div><div><p className="eyebrow">Coin reserve</p><p className="font-display text-2xl font-extrabold text-[#ffd27a]">{user.coins.toLocaleString()}</p><p className="text-[.65rem] text-muted">Spend earned, never bought.</p></div></div></header>
    <div className="vault-toolbar"><div className="flex gap-2 overflow-x-auto pb-1">{categories.map((item) => <button key={item} onClick={() => setCategory(item)} className={`vault-filter whitespace-nowrap ${category === item ? 'vault-filter-active' : ''}`}>{item}</button>)}</div><div className="hidden items-center gap-2 text-xs text-muted sm:flex"><Gem size={14} className="text-lime" /> {filteredItems.length} relics in view</div></div>
    <div className="vault-grid mt-6">{filteredItems.map((item, index) => <ShopItem key={item.id} item={item} index={index} user={user} onInspect={setSelectedItem} onPurchase={onPurchase} onEquip={onEquip} canAfford={user.coins >= item.price} />)}</div>
    {selectedItem && <ArtifactModal item={selectedItem} user={user} onClose={() => setSelectedItem(null)} onPurchase={onPurchase} onEquip={onEquip} canAfford={user.coins >= selectedItem.price} />}
    <div className="mt-10 flex items-start gap-4 border-t border-white/8 pt-7"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-lime text-ink"><Gift size={20} /></div><div><p className="font-display text-lg font-bold">Some artifacts are discovered, not bought.</p><p className="mt-1 max-w-2xl text-sm leading-6 text-muted">Keep your streak alive and open milestone chests for the rarest frames, effects, and trophy displays. Your work determines what your character can wear.</p></div></div>
  </div></div>;
}

function ShopItem({ item, index, user, onInspect, onPurchase, onEquip, canAfford }) {
  const rarity = item.rarity || 'Common';
  const style = rarityStyles[rarity] || rarityStyles.Common;
  const locked = item.locked || item.unlocksAt;
  return <motion.article initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * .05 }} whileHover={{ y: -7, rotate: index % 2 ? .35 : -.35 }} onClick={() => onInspect(item)} className={`group overflow-hidden border bg-panel ${style.border} ${style.glow} vault-artifact-card`}>
    <ArtifactPreview item={item} user={user} style={style} rarity={rarity} variant={index % 5} />
    <div className="p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-display font-bold">{item.name}</p><p className="mt-1 text-xs text-muted">{item.category} · {item.material ? `${item.material} artifact` : locked ? 'Discovery item' : 'Vault item'}</p></div><span className={`font-mono text-[.6rem] font-bold tracking-widest ${getRarityColor(rarity)}`}>{rarity.toUpperCase()}</span></div><p className="mt-3 line-clamp-2 text-xs leading-5 text-muted">{item.detail || 'A distinct relic for a distinct run.'}</p>
         {locked ? <div className="mt-5 flex items-center gap-2 rounded-xl bg-white/5 px-3 py-2.5 text-xs font-semibold text-muted"><Lock size={13} /> {item.unlocksAt || 'Unlock in Chest'}</div> : item.owned ? <div className="mt-5 flex items-center justify-between rounded-xl bg-[#5bdc96]/10 px-3 py-2.5 text-xs font-bold text-[#8ff0b6]"><span className="flex items-center gap-2"><Check size={14} /> Owned</span><button onClick={(event) => { event.stopPropagation(); playEquip(); onEquip(item.id, item.equipped); }} className="text-lime-soft hover:underline">{item.equipped ? 'Unequip' : 'Equip'}</button></div> : item.catalogOnly ? <div className="mt-5 flex items-center gap-2 rounded-xl bg-white/5 px-3 py-2.5 text-xs font-semibold text-muted"><Lock size={13} /> {item.unlocksAt || 'Unlock in Chest'}</div> : <button onClick={(event) => { event.stopPropagation(); playVaultPurchase(); onPurchase(item.id); }} disabled={!canAfford} className={`mt-5 flex w-full items-center justify-center gap-2 rounded-xl py-2.5 text-xs font-bold transition ${canAfford ? 'bg-white/8 text-white hover:bg-lime hover:text-ink' : 'cursor-not-allowed bg-white/5 text-muted'}`}><Coins size={14} className="text-[#ffd27a]" /> {item.price.toLocaleString()} coins</button>}</div>
  </motion.article>;
}

function ArtifactModal({ item, user, onClose, onPurchase, onEquip, canAfford }) {
  const rarity = item.rarity || 'Common';
  const locked = item.locked || item.unlocksAt || item.catalogOnly;
  return <div className="fixed inset-0 z-50 grid place-items-center bg-black/75 p-4 backdrop-blur-sm" onClick={onClose}><motion.div initial={{ opacity: 0, y: 18, scale: .96 }} animate={{ opacity: 1, y: 0, scale: 1 }} className="vault-inspect-modal" onClick={(event) => event.stopPropagation()}><button onClick={onClose} className="icon-button absolute right-4 top-4 z-10" aria-label="Close artifact inspector"><X size={17} /></button><div className="vault-inspect-art"><ArtifactPreview item={item} user={user} style={rarityStyles[rarity] || rarityStyles.Common} rarity={rarity} variant={Math.abs(item.id.length) % 5} /></div><div className="vault-inspect-copy"><p className={`eyebrow ${getRarityColor(rarity)}`}>{rarity} artifact · {item.category}</p><h2 className="mt-2 font-display text-3xl font-extrabold">{item.name}</h2><p className="mt-3 text-sm leading-7 text-muted">{item.detail || 'A distinct relic for a distinct run.'}</p><div className="vault-inspect-stats"><span><small>RARITY</small><strong className={getRarityColor(rarity)}>{rarity.toUpperCase()}</strong></span><span><small>ORIGIN</small><strong>{item.material ? item.material.toUpperCase() : 'VAULT DROP'}</strong></span><span><small>STATUS</small><strong>{item.owned ? item.equipped ? 'EQUIPPED' : 'OWNED' : locked ? 'LOCKED' : 'AVAILABLE'}</strong></span></div>{item.owned ? <button onClick={() => { playEquip(); onEquip(item.id, item.equipped); onClose(); }} className="btn-primary mt-6 flex w-full items-center justify-center gap-2"><Sparkles size={15} /> {item.equipped ? 'Unequip artifact' : 'Equip artifact'}</button> : !locked ? <button onClick={() => { playVaultPurchase(); onPurchase(item.id); onClose(); }} disabled={!canAfford} className="btn-primary mt-6 flex w-full items-center justify-center gap-2 disabled:cursor-not-allowed disabled:opacity-50"><Coins size={15} /> Claim for {item.price.toLocaleString()} coins</button> : <div className="mt-6 flex items-center gap-2 rounded-xl bg-white/5 px-4 py-3 text-xs font-semibold text-muted"><Lock size={14} /> {item.unlocksAt || 'Unlock in a future chest'}</div>}</div></motion.div></div>;
}

function ArtifactPreview({ item, user, style, rarity, variant }) {
  const category = item.category;
  const ArtifactIcon = { Badge: BadgeCheck, 'Trophy Display': Crown, 'XP Effect': Orbit, Theme: Palette, 'Avatar Effect': Sparkles, Nameplate: ShoppingBag }[category] || Shield;
  return <div className={`relative flex h-48 items-center justify-center overflow-hidden bg-gradient-to-br ${style.panel} artifact-preview artifact-preview-${variant}`}>
    <div className="artifact-stars" />
    {category === 'Profile Frame' ? <div style={{ borderColor: frameMaterialColors[item.material || 'wood'] }} className={`artifact-frame artifact-frame-material-${item.material || 'wood'} artifact-frame-v${variant} relative grid h-28 w-28 place-items-center`}><i /><i /><Avatar avatar={user.avatar} size="lg" border={false} /></div> : category === 'Nameplate' ? <div className={`artifact-nameplate artifact-nameplate-${rarity.toLowerCase()} artifact-nameplate-v${variant} border px-5 py-3 text-center`}><div className="flex items-center justify-center gap-2"><Star size={11} /><span className="font-mono text-[.58rem] tracking-[.24em]">LEVEL {user.level}</span><Star size={11} /></div><p className="mt-1 font-display text-lg font-extrabold">@{user.username || 'grinder'}</p></div> : category === 'Avatar Effect' ? <div className={`artifact-avatar-effect artifact-avatar-effect-${rarity.toLowerCase()} artifact-avatar-v${variant} relative rounded-full p-3 ${style.glow}`}><span /><span /><Avatar avatar={user.avatar} size="lg" /></div> : category === 'Theme' ? <div className={`artifact-theme artifact-theme-${rarity.toLowerCase()} artifact-theme-v${variant} w-48 border p-3 ${style.border}`}><div className="flex items-center gap-2"><Avatar avatar={user.avatar} size="xs" border={false} /><span className="text-xs font-bold text-white">@{user.username || 'grinder'}</span></div><div className="mt-3 h-2 w-20 rounded bg-white/70" /><div className="mt-2 h-2 w-32 rounded bg-white/25" /><div className="mt-4 h-10 border border-white/20 bg-black/25" /></div> : category === 'XP Effect' ? <div className={`artifact-xp-effect artifact-xp-v${variant} text-center`}><span /><span /><div className="flex items-center justify-center gap-2"><Zap size={18} className="text-white" /><span className="font-display text-3xl font-extrabold text-white">+120</span></div><span className="mt-1 block font-mono text-[.58rem] tracking-[.24em] text-white/70">XP GAINED</span></div> : category === 'Badge' ? <div className={`artifact-badge artifact-badge-${rarity.toLowerCase()} artifact-badge-v${variant} grid h-24 w-24 place-items-center`}><BadgeCheck size={42} strokeWidth={1.2} /></div> : category === 'Trophy Display' ? <div className={`artifact-trophy artifact-trophy-${rarity.toLowerCase()} artifact-trophy-v${variant} relative flex h-28 w-24 items-end justify-center`}><Trophy size={62} strokeWidth={1.1} /><span className="absolute bottom-0 h-2 w-20 rounded-full bg-white/30" /></div> : <div className={`relative grid h-24 w-24 place-items-center rounded-[2rem] border ${style.border} ${style.artifact} ${style.glow}`}><ArtifactIcon size={42} strokeWidth={1.2} className="text-white" /></div>}
    <span className="absolute bottom-3 left-3 rounded-full border border-white/20 bg-black/25 px-2 py-1 font-mono text-[.58rem] font-bold tracking-widest text-white/80">{rarity}</span>
  </div>;
}
