import { useMemo, useState } from 'react';
import { motion } from 'framer-motion';
import { Check, Coins, Gift, Lock, Sparkles } from 'lucide-react';
import { getRarityColor } from '../data/mockData';

const categories = ['All', 'Profile Frame', 'Nameplate', 'Theme', 'XP Effect', 'Avatar Effect', 'Badge'];

export default function Shop({ user, items, onPurchase }) {
  const [category, setCategory] = useState('All');
  const filteredItems = useMemo(() => category === 'All' ? items : items.filter((item) => item.category === category), [category, items]);
  return <div className="min-h-screen bg-ink"><div className="mx-auto max-w-6xl px-5 py-7 sm:px-8 lg:px-12 lg:py-10"><header className="flex flex-col justify-between gap-5 border-b border-white/8 pb-7 sm:flex-row sm:items-end"><div><p className="eyebrow">The Vault</p><h1 className="mt-2 font-display text-4xl font-extrabold">Make it yours.</h1><p className="mt-2 text-sm text-muted">Cosmetics earned through real progress. No shortcuts, no power-ups.</p></div><div className="flex items-center gap-3 rounded-2xl border border-[#ffd27a]/20 bg-[#ffd27a]/8 px-4 py-3"><Coins size={18} className="text-[#ffd27a]" /><div><p className="eyebrow">Your balance</p><p className="font-display text-lg font-extrabold text-[#ffd27a]">{user.coins.toLocaleString()}</p></div></div></header><div className="mt-7 flex gap-2 overflow-x-auto pb-1">{categories.map((item) => <button key={item} onClick={() => setCategory(item)} className={`whitespace-nowrap rounded-full border px-3 py-1.5 text-xs font-semibold transition ${category === item ? 'border-lime/40 bg-lime/10 text-lime-soft' : 'border-white/10 bg-white/[.03] text-muted hover:bg-white/[.07]'}`}>{item}</button>)}</div><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{filteredItems.map((item, index) => <ShopItem key={item.id} item={item} index={index} onPurchase={onPurchase} canAfford={user.coins >= item.price} />)}</div><div className="mt-8 grid gap-4 md:grid-cols-2"><div className="rounded-2xl border border-lime/20 bg-gradient-to-br from-[#1d2d20] to-panel p-5"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-lime text-ink"><Gift size={19} /></div><div><p className="font-display font-bold">Mystery chest</p><p className="text-xs text-muted">A surprise for consistent grinders</p></div></div><p className="mt-4 text-sm leading-6 text-slate-300">Some of the rarest cosmetics can’t be bought. Keep your streak alive and watch for milestone drops.</p></div><div className="rounded-2xl border border-white/10 bg-panel p-5"><div className="flex items-center gap-2"><Sparkles size={16} className="text-lime" /><p className="eyebrow">Economy rule</p></div><p className="mt-4 font-display text-lg font-bold">Earned looks better.</p><p className="mt-1 text-sm leading-6 text-muted">Cosmetics express progress, but never give gameplay power. Your work stays the reward.</p></div></div></div></div>;
}

function ShopItem({ item, index, onPurchase, canAfford }) { return <motion.article initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * .05 }} className={`group relative overflow-hidden rounded-2xl border bg-panel p-4 ${item.locked ? 'border-white/8' : 'border-white/10 hover:border-lime/25'}`}><div className="flex h-36 items-center justify-center rounded-xl bg-gradient-to-br from-white/[.06] to-transparent text-7xl transition duration-300 group-hover:scale-[1.03]">{item.preview}</div><div className="mt-4 flex items-start justify-between gap-3"><div><p className="font-display font-bold">{item.name}</p><p className="mt-1 text-xs text-muted">{item.category}</p></div><span className={`font-mono text-[.6rem] font-bold ${getRarityColor(item.rarity)}`}>{item.rarity.toUpperCase()}</span></div>{item.locked ? <div className="mt-5 flex items-center gap-2 rounded-xl bg-white/5 px-3 py-2 text-xs text-muted"><Lock size={13} /> {item.unlocksAt}</div> : item.owned ? <div className="mt-5 flex items-center justify-center gap-2 rounded-xl bg-[#5bdc96]/10 py-2.5 text-xs font-bold text-[#8ff0b6]"><Check size={14} /> Owned</div> : <button onClick={() => onPurchase(item.id)} disabled={!canAfford} className={`mt-5 flex w-full items-center justify-center gap-2 rounded-xl py-2.5 text-xs font-bold transition ${canAfford ? 'bg-white/8 text-white hover:bg-lime hover:text-ink' : 'cursor-not-allowed bg-white/5 text-muted'}`}><Coins size={14} className="text-[#ffd27a]" /> {item.price.toLocaleString()}</button>}</motion.article>; }
